# Generated by Django 4.2.6 on 2023-10-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество просмотров'),
        ),
    ]
