# Generated by Django 4.2.6 on 2023-11-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_change',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, verbose_name='название продукта'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=5, null=True, verbose_name='номер версии')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='название версии')),
                ('is_active', models.BooleanField(choices=[(True, 'активная'), (False, 'не активная')], verbose_name='признак текущей версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('number',),
            },
        ),
    ]
