# Generated by Django 4.2.6 on 2023-11-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=120, verbose_name='название продукта'),
        ),
    ]
